services:
  - type: web
    name: htmlweb-dev
    env: node
    plan: starter
    buildCommand: npm install && npm run build && cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOSTNAME
        value: "0.0.0.0"
      - key: MONGODB_URI
        sync: false
      - key: OAUTH_CLIENT_ID
        sync: false
      - key: OAUTH_CLIENT_SECRET
        sync: false
      - key: DEFAULT_HF_TOKEN
        sync: false
      - key: HF_TOKEN
        sync: false